<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'brand' => 'Temporibus culpa.',
                'sku' => 'ISNMg8OqAE',
                'name' => 'Veniam dolorum.',
                'slug' => 'veniam-dolorum',
                'description' => 'Est numquam quia aut cumque consequuntur quia consectetur earum animi quibusdam iste dolor quam dolorum eos alias quaerat reiciendis laborum in omnis amet eos sequi excepturi voluptates eligendi.',
                'quantity' => 72,
                'weight' => NULL,
                'price' => '154.00',
                'sale_price' => NULL,
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 1,
                'created_at' => '2020-08-08 13:55:10',
                'updated_at' => '2020-08-08 13:55:10',
            ),
            1 => 
            array (
                'id' => 2,
                'brand' => 'Accusantium.',
                'sku' => 't6WDTtThy1',
                'name' => 'Adipisci quas.',
                'slug' => 'adipisci-quas',
                'description' => 'Aperiam sunt odit quidem cupiditate officia in non nihil et eos ratione quae nostrum.',
                'quantity' => 81,
                'weight' => NULL,
                'price' => '590.00',
                'sale_price' => NULL,
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 3,
                'created_at' => '2020-08-08 13:55:10',
                'updated_at' => '2020-08-08 13:55:10',
            ),
            2 => 
            array (
                'id' => 3,
                'brand' => 'Fugit.',
                'sku' => '1nIxqPoPAQ',
                'name' => 'Quae aut architecto.',
                'slug' => 'quae-aut-architecto',
                'description' => 'Minima eum quia necessitatibus aut dolor facere aut ipsam qui odio consequuntur earum nesciunt sapiente aut dolor molestiae rerum modi excepturi ut enim numquam praesentium quis.',
                'quantity' => 45,
                'weight' => NULL,
                'price' => '830.00',
                'sale_price' => '483.00',
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 1,
                'created_at' => '2020-08-08 13:55:10',
                'updated_at' => '2020-08-08 13:55:10',
            ),
            3 => 
            array (
                'id' => 4,
                'brand' => 'Autem cum.',
                'sku' => 'y26QH42k0R',
                'name' => 'Ex magnam aut.',
                'slug' => 'ex-magnam-aut',
                'description' => 'Labore adipisci minus est molestias blanditiis nobis expedita et ex culpa magnam eius sed rerum minus nisi alias consequatur voluptatem distinctio occaecati nulla aut modi.',
                'quantity' => 40,
                'weight' => NULL,
                'price' => '526.00',
                'sale_price' => '333.00',
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 1,
                'created_at' => '2020-08-08 13:55:11',
                'updated_at' => '2020-08-08 13:55:11',
            ),
            4 => 
            array (
                'id' => 5,
                'brand' => 'Perspiciatis voluptate.',
                'sku' => 'gDFd0emssh',
                'name' => 'Praesentium ad.',
                'slug' => 'praesentium-ad',
                'description' => 'Aut animi possimus beatae a animi quia ipsa temporibus quae quis aliquid nam eum distinctio voluptas.',
                'quantity' => 100,
                'weight' => NULL,
                'price' => '239.00',
                'sale_price' => NULL,
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 2,
                'created_at' => '2020-08-08 13:55:11',
                'updated_at' => '2020-08-08 13:55:11',
            ),
            5 => 
            array (
                'id' => 6,
                'brand' => 'Blanditiis unde.',
                'sku' => 'uXhsK6aLxY',
                'name' => 'Alias quibusdam.',
                'slug' => 'alias-quibusdam',
                'description' => 'Ullam quis voluptatibus rerum cum aut illum qui quod corporis qui enim labore quo sed quas ex eum error et ratione numquam voluptatem itaque dolores.',
                'quantity' => 39,
                'weight' => NULL,
                'price' => '930.00',
                'sale_price' => '447.00',
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 2,
                'created_at' => '2020-08-08 13:55:11',
                'updated_at' => '2020-08-08 13:55:11',
            ),
            6 => 
            array (
                'id' => 7,
                'brand' => 'Impedit enim.',
                'sku' => 'DMwdiPK6VE',
                'name' => 'Nulla dolorem ipsam.',
                'slug' => 'nulla-dolorem-ipsam',
                'description' => 'At occaecati exercitationem eius architecto quod voluptatem ut velit culpa a quis debitis voluptatem assumenda sequi facilis voluptas dignissimos asperiores et qui vel.',
                'quantity' => 99,
                'weight' => NULL,
                'price' => '213.00',
                'sale_price' => NULL,
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 2,
                'created_at' => '2020-08-08 13:55:11',
                'updated_at' => '2020-08-08 13:55:11',
            ),
            7 => 
            array (
                'id' => 8,
                'brand' => 'Ex dolore.',
                'sku' => 'ETvfGc0oIa',
                'name' => 'Natus perferendis.',
                'slug' => 'natus-perferendis',
                'description' => 'Occaecati quasi aut aut adipisci quia vel quae ducimus earum nulla vel quia voluptatem veniam porro nobis possimus ducimus nostrum ea.',
                'quantity' => 61,
                'weight' => NULL,
                'price' => '612.00',
                'sale_price' => NULL,
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 2,
                'created_at' => '2020-08-08 13:55:11',
                'updated_at' => '2020-08-08 13:55:11',
            ),
            8 => 
            array (
                'id' => 9,
                'brand' => 'In similique.',
                'sku' => 'MVM0DkUyzK',
                'name' => 'Totam dicta.',
                'slug' => 'totam-dicta',
                'description' => 'Omnis in et doloribus ducimus officia qui perferendis et et sed temporibus voluptatem nihil tempora ab ex aut aspernatur.',
                'quantity' => 30,
                'weight' => NULL,
                'price' => '128.00',
                'sale_price' => NULL,
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 1,
                'created_at' => '2020-08-08 13:55:11',
                'updated_at' => '2020-08-08 13:55:11',
            ),
            9 => 
            array (
                'id' => 10,
                'brand' => 'Minima.',
                'sku' => 'gMZzDTfmDK',
                'name' => 'Excepturi itaque.',
                'slug' => 'excepturi-itaque',
                'description' => 'Et voluptas dolor distinctio voluptates blanditiis dolores eos rem non animi omnis officia accusamus quos rerum accusamus.',
                'quantity' => 41,
                'weight' => NULL,
                'price' => '214.00',
                'sale_price' => '446.00',
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 1,
                'created_at' => '2020-08-08 13:55:11',
                'updated_at' => '2020-08-08 13:55:11',
            ),
            10 => 
            array (
                'id' => 11,
                'brand' => 'Illo laudantium.',
                'sku' => 'S4EFSrLLWp',
                'name' => 'Doloremque soluta harum.',
                'slug' => 'doloremque-soluta-harum',
                'description' => 'Et qui id deserunt ipsam quasi consequatur aut neque eos dignissimos suscipit omnis omnis consequatur rerum.',
                'quantity' => 15,
                'weight' => NULL,
                'price' => '808.00',
                'sale_price' => NULL,
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 2,
                'created_at' => '2020-08-08 13:55:11',
                'updated_at' => '2020-08-08 13:55:11',
            ),
            11 => 
            array (
                'id' => 12,
                'brand' => 'Eum temporibus.',
                'sku' => 'i6hLmJCA7d',
                'name' => 'Sint et.',
                'slug' => 'sint-et',
                'description' => 'Impedit magnam sed vitae adipisci et rerum ea aliquam ipsum rerum ipsa quaerat eos non numquam reiciendis eum commodi totam possimus ut mollitia ratione animi.',
                'quantity' => 22,
                'weight' => NULL,
                'price' => '281.00',
                'sale_price' => '246.00',
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 2,
                'created_at' => '2020-08-08 13:55:11',
                'updated_at' => '2020-08-08 13:55:11',
            ),
            12 => 
            array (
                'id' => 13,
                'brand' => 'Recusandae.',
                'sku' => 'pbYN9gbKVC',
                'name' => 'Molestias aut est.',
                'slug' => 'molestias-aut-est',
                'description' => 'Eum quia libero repudiandae dolores illo dolor corrupti enim odit quis molestias nostrum vel ut in omnis nostrum fuga delectus accusamus rem sit.',
                'quantity' => 79,
                'weight' => NULL,
                'price' => '895.00',
                'sale_price' => NULL,
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 2,
                'created_at' => '2020-08-08 13:55:12',
                'updated_at' => '2020-08-08 13:55:12',
            ),
            13 => 
            array (
                'id' => 14,
                'brand' => 'Error enim.',
                'sku' => '3bsH9oidUC',
                'name' => 'Minima nesciunt.',
                'slug' => 'minima-nesciunt',
                'description' => 'Sed autem quia aut rerum explicabo nostrum voluptate aut odio possimus tenetur aut voluptatem voluptatem optio ad dolorem asperiores sed sit tempore numquam vel neque quo veritatis rerum.',
                'quantity' => 64,
                'weight' => NULL,
                'price' => '714.00',
                'sale_price' => NULL,
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 2,
                'created_at' => '2020-08-08 13:55:12',
                'updated_at' => '2020-08-08 13:55:12',
            ),
            14 => 
            array (
                'id' => 15,
                'brand' => 'Ipsa.',
                'sku' => 'XW2xMWCQX8',
                'name' => 'Error molestiae velit.',
                'slug' => 'error-molestiae-velit',
                'description' => 'Minima eos eius dolor id atque facere dolor adipisci voluptas corporis quae similique qui cumque consequatur incidunt sequi culpa optio vel quidem omnis.',
                'quantity' => 56,
                'weight' => NULL,
                'price' => '851.00',
                'sale_price' => '355.00',
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 2,
                'created_at' => '2020-08-08 13:55:12',
                'updated_at' => '2020-08-08 13:55:12',
            ),
            15 => 
            array (
                'id' => 16,
                'brand' => 'Dolor.',
                'sku' => 'KehM9lqueb',
                'name' => 'Magni et.',
                'slug' => 'magni-et',
                'description' => 'Quia occaecati et vel sapiente animi vel reiciendis minima qui fugit dignissimos similique ab officiis expedita aut iusto atque aut excepturi possimus sint beatae.',
                'quantity' => 63,
                'weight' => NULL,
                'price' => '438.00',
                'sale_price' => NULL,
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 1,
                'created_at' => '2020-08-08 13:55:12',
                'updated_at' => '2020-08-08 13:55:12',
            ),
            16 => 
            array (
                'id' => 17,
                'brand' => 'Ea.',
                'sku' => 'UP5v9TvDGU',
                'name' => 'Natus animi ut.',
                'slug' => 'natus-animi-ut',
                'description' => 'Ipsam ratione et iusto sapiente perspiciatis voluptatem voluptatibus debitis molestiae dolore reiciendis qui ea.',
                'quantity' => 35,
                'weight' => NULL,
                'price' => '423.00',
                'sale_price' => '167.00',
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 3,
                'created_at' => '2020-08-08 13:55:12',
                'updated_at' => '2020-08-08 13:55:12',
            ),
            17 => 
            array (
                'id' => 18,
                'brand' => 'Quae omnis.',
                'sku' => 'Co0tpomCgZ',
                'name' => 'Minus nam.',
                'slug' => 'minus-nam',
                'description' => 'Minima quia repudiandae enim doloremque ut velit vel sit qui quas voluptatibus ut ut laborum earum sint similique voluptatem dolore perferendis cupiditate et cum.',
                'quantity' => 75,
                'weight' => NULL,
                'price' => '855.00',
                'sale_price' => '364.00',
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 1,
                'created_at' => '2020-08-08 13:55:13',
                'updated_at' => '2020-08-08 13:55:13',
            ),
            18 => 
            array (
                'id' => 19,
                'brand' => 'Magni.',
                'sku' => 'tn5Ry0QSAN',
                'name' => 'Ea ab consequatur.',
                'slug' => 'ea-ab-consequatur',
                'description' => 'Cumque fugit dolore dolorum perspiciatis et et incidunt perspiciatis nemo distinctio voluptatem iusto nemo qui libero facere.',
                'quantity' => 35,
                'weight' => NULL,
                'price' => '329.00',
                'sale_price' => '324.00',
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 2,
                'created_at' => '2020-08-08 13:55:13',
                'updated_at' => '2020-08-08 13:55:13',
            ),
            19 => 
            array (
                'id' => 20,
                'brand' => 'Ut ab.',
                'sku' => 'xycAdY4gb8',
                'name' => 'Molestias sunt.',
                'slug' => 'molestias-sunt',
                'description' => 'Sed quia eum ut similique laborum quam et error illum sed veritatis amet enim aut vel saepe veniam enim et.',
                'quantity' => 34,
                'weight' => NULL,
                'price' => '427.00',
                'sale_price' => '86.00',
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 1,
                'created_at' => '2020-08-08 13:55:13',
                'updated_at' => '2020-08-08 13:55:13',
            ),
            20 => 
            array (
                'id' => 21,
                'brand' => 'Molestiae.',
                'sku' => 'fofTXt6XxX',
                'name' => 'Minima rerum nobis.',
                'slug' => 'minima-rerum-nobis',
                'description' => 'Nostrum eveniet fuga eligendi rerum molestiae cupiditate animi similique non impedit tenetur sapiente consequuntur tenetur architecto.',
                'quantity' => 65,
                'weight' => NULL,
                'price' => '518.00',
                'sale_price' => NULL,
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 2,
                'created_at' => '2020-08-08 13:55:13',
                'updated_at' => '2020-08-08 13:55:13',
            ),
            21 => 
            array (
                'id' => 22,
                'brand' => 'Placeat molestias.',
                'sku' => '7U5CcZkgdr',
                'name' => 'Quas velit pariatur.',
                'slug' => 'quas-velit-pariatur',
                'description' => 'Corporis quo voluptate sapiente numquam vel repellendus aut rerum exercitationem minus ducimus in rem consequatur culpa voluptas iste vel totam repellat ea est quasi cumque rerum voluptas.',
                'quantity' => 73,
                'weight' => NULL,
                'price' => '857.00',
                'sale_price' => NULL,
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 1,
                'created_at' => '2020-08-08 13:55:13',
                'updated_at' => '2020-08-08 13:55:13',
            ),
            22 => 
            array (
                'id' => 23,
                'brand' => 'Ex nobis.',
                'sku' => 'EKqnZ2CItb',
                'name' => 'Laudantium totam assumenda.',
                'slug' => 'laudantium-totam-assumenda',
                'description' => 'Praesentium nam ea delectus qui ipsam omnis necessitatibus quidem sed numquam quod minima reiciendis sed et laborum sunt est necessitatibus.',
                'quantity' => 66,
                'weight' => NULL,
                'price' => '990.00',
                'sale_price' => NULL,
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 1,
                'created_at' => '2020-08-08 13:55:13',
                'updated_at' => '2020-08-08 13:55:13',
            ),
            23 => 
            array (
                'id' => 24,
                'brand' => 'In id.',
                'sku' => 'LmApOLE6Qc',
                'name' => 'Ut vel occaecati.',
                'slug' => 'ut-vel-occaecati',
                'description' => 'Omnis temporibus illum dignissimos cumque non non consequatur repellat non est odit enim pariatur.',
                'quantity' => 37,
                'weight' => NULL,
                'price' => '784.00',
                'sale_price' => NULL,
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 3,
                'created_at' => '2020-08-08 13:55:14',
                'updated_at' => '2020-08-08 13:55:14',
            ),
            24 => 
            array (
                'id' => 25,
                'brand' => 'Ipsa.',
                'sku' => 'W9bsh97tor',
                'name' => 'Cumque blanditiis et.',
                'slug' => 'cumque-blanditiis-et',
                'description' => 'Recusandae consequatur soluta aut laudantium rerum provident architecto animi sed sit dolores occaecati consequatur recusandae qui tempore labore velit tenetur quo ab.',
                'quantity' => 94,
                'weight' => NULL,
                'price' => '810.00',
                'sale_price' => NULL,
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 1,
                'created_at' => '2020-08-08 13:55:14',
                'updated_at' => '2020-08-08 13:55:14',
            ),
            25 => 
            array (
                'id' => 26,
                'brand' => 'Ducimus consequatur.',
                'sku' => 'a3SEvIUsQK',
                'name' => 'Dignissimos aliquam.',
                'slug' => 'dignissimos-aliquam',
                'description' => 'Laborum commodi odio voluptatem perspiciatis quam vel est excepturi maiores dolores repudiandae qui inventore.',
                'quantity' => 33,
                'weight' => NULL,
                'price' => '167.00',
                'sale_price' => NULL,
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 1,
                'created_at' => '2020-08-08 13:55:14',
                'updated_at' => '2020-08-08 13:55:14',
            ),
            26 => 
            array (
                'id' => 27,
                'brand' => 'Error tempore.',
                'sku' => 'hxPHrUSxsi',
                'name' => 'Quidem quia.',
                'slug' => 'quidem-quia',
                'description' => 'Quia labore delectus saepe voluptatem nulla quam omnis beatae et id maiores voluptatum ab libero dolorum commodi quas.',
                'quantity' => 65,
                'weight' => NULL,
                'price' => '642.00',
                'sale_price' => '422.00',
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 3,
                'created_at' => '2020-08-08 13:55:14',
                'updated_at' => '2020-08-08 13:55:14',
            ),
            27 => 
            array (
                'id' => 28,
                'brand' => 'Tempore praesentium.',
                'sku' => '9XkugwlZdZ',
                'name' => 'Maxime quod.',
                'slug' => 'maxime-quod',
                'description' => 'Aliquid consequatur mollitia debitis dolorem blanditiis tempore rerum nemo et nihil voluptatem impedit iusto neque qui et et et vel.',
                'quantity' => 31,
                'weight' => NULL,
                'price' => '701.00',
                'sale_price' => '492.00',
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 1,
                'created_at' => '2020-08-08 13:55:14',
                'updated_at' => '2020-08-08 13:55:14',
            ),
            28 => 
            array (
                'id' => 29,
                'brand' => 'Rem.',
                'sku' => 'HcXT9XKj9M',
                'name' => 'Odit quis nobis.',
                'slug' => 'odit-quis-nobis',
                'description' => 'Quia sed culpa omnis reprehenderit et est dolor quisquam eos dolorem explicabo placeat dolores neque nisi in est deserunt.',
                'quantity' => 92,
                'weight' => NULL,
                'price' => '354.00',
                'sale_price' => NULL,
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 1,
                'created_at' => '2020-08-08 13:55:14',
                'updated_at' => '2020-08-08 13:55:14',
            ),
            29 => 
            array (
                'id' => 30,
                'brand' => 'Et magni.',
                'sku' => 'KWDbbbi5x3',
                'name' => 'Numquam non.',
                'slug' => 'numquam-non',
                'description' => 'Deleniti nisi omnis nulla et deleniti quibusdam nostrum et illum aut eum voluptatum quam est rerum et quibusdam qui dolor et officiis dolore.',
                'quantity' => 94,
                'weight' => NULL,
                'price' => '837.00',
                'sale_price' => '111.00',
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 1,
                'created_at' => '2020-08-08 13:55:14',
                'updated_at' => '2020-08-08 13:55:14',
            ),
            30 => 
            array (
                'id' => 31,
                'brand' => 'Corrupti quisquam.',
                'sku' => 'qCOO7guZXq',
                'name' => 'Est voluptatibus.',
                'slug' => 'est-voluptatibus',
                'description' => 'Reiciendis nulla odit numquam dolorum ipsa veritatis omnis consequatur id dicta quos quibusdam dicta eos ut soluta necessitatibus qui saepe ea voluptatem voluptas eius magnam numquam qui.',
                'quantity' => 93,
                'weight' => NULL,
                'price' => '117.00',
                'sale_price' => NULL,
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 1,
                'created_at' => '2020-08-08 13:55:14',
                'updated_at' => '2020-08-08 13:55:14',
            ),
            31 => 
            array (
                'id' => 32,
                'brand' => 'Eligendi aut.',
                'sku' => '0gKsOYJd5r',
                'name' => 'Odio voluptatum.',
                'slug' => 'odio-voluptatum',
                'description' => 'Esse labore et vero dolorum omnis ut labore officiis voluptas amet rerum dolores.',
                'quantity' => 14,
                'weight' => NULL,
                'price' => '980.00',
                'sale_price' => '54.00',
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 3,
                'created_at' => '2020-08-08 13:55:14',
                'updated_at' => '2020-08-08 13:55:14',
            ),
            32 => 
            array (
                'id' => 33,
                'brand' => 'Animi quia.',
                'sku' => 'RkiDJHFTFy',
                'name' => 'Non et.',
                'slug' => 'non-et',
                'description' => 'Laborum earum itaque ad delectus repellendus iste placeat laborum quibusdam repellat molestias corporis debitis.',
                'quantity' => 13,
                'weight' => NULL,
                'price' => '779.00',
                'sale_price' => '111.00',
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 2,
                'created_at' => '2020-08-08 13:55:15',
                'updated_at' => '2020-08-08 13:55:15',
            ),
            33 => 
            array (
                'id' => 34,
                'brand' => 'Iure.',
                'sku' => 'oKndnObDTw',
                'name' => 'Suscipit nihil aut.',
                'slug' => 'suscipit-nihil-aut',
                'description' => 'Sunt rerum et et voluptas perferendis ipsam quae provident quisquam ut reprehenderit harum qui omnis laboriosam tempora similique aliquam fuga asperiores omnis.',
                'quantity' => 33,
                'weight' => NULL,
                'price' => '201.00',
                'sale_price' => '307.00',
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 1,
                'created_at' => '2020-08-08 13:55:15',
                'updated_at' => '2020-08-08 13:55:15',
            ),
            34 => 
            array (
                'id' => 35,
                'brand' => 'Ullam ut.',
                'sku' => '34IgYtns1x',
                'name' => 'Itaque assumenda.',
                'slug' => 'itaque-assumenda',
                'description' => 'Et sed qui distinctio ipsum qui dolore saepe qui magnam asperiores itaque laborum sint quaerat nesciunt ea ut aut sint culpa necessitatibus ea est ipsam.',
                'quantity' => 32,
                'weight' => NULL,
                'price' => '772.00',
                'sale_price' => NULL,
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 1,
                'created_at' => '2020-08-08 13:55:15',
                'updated_at' => '2020-08-08 13:55:15',
            ),
            35 => 
            array (
                'id' => 36,
                'brand' => 'Debitis nihil.',
                'sku' => 'pTXvDwIAWc',
                'name' => 'Molestiae ex commodi.',
                'slug' => 'molestiae-ex-commodi',
                'description' => 'Cupiditate sed sit enim quasi consequuntur ea qui numquam temporibus natus illum consequuntur possimus ea perspiciatis illo enim tenetur esse excepturi.',
                'quantity' => 44,
                'weight' => NULL,
                'price' => '270.00',
                'sale_price' => NULL,
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 2,
                'created_at' => '2020-08-08 13:55:15',
                'updated_at' => '2020-08-08 13:55:15',
            ),
            36 => 
            array (
                'id' => 37,
                'brand' => 'Natus a.',
                'sku' => 'U9tb4S04CB',
                'name' => 'Distinctio dolores.',
                'slug' => 'distinctio-dolores',
                'description' => 'Blanditiis corrupti est et in numquam accusamus voluptates fugiat minus aspernatur natus neque sed minus.',
                'quantity' => 99,
                'weight' => NULL,
                'price' => '811.00',
                'sale_price' => NULL,
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 2,
                'created_at' => '2020-08-08 13:55:15',
                'updated_at' => '2020-08-08 13:55:15',
            ),
            37 => 
            array (
                'id' => 38,
                'brand' => 'Dolorem enim.',
                'sku' => 'zJSUpbDhMU',
                'name' => 'Est saepe.',
                'slug' => 'est-saepe',
                'description' => 'Qui voluptas numquam ut dignissimos consequatur reiciendis rerum tenetur ipsa a cumque voluptates non libero iusto sunt non illo a praesentium quo nobis.',
                'quantity' => 30,
                'weight' => NULL,
                'price' => '169.00',
                'sale_price' => NULL,
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 1,
                'created_at' => '2020-08-08 13:55:15',
                'updated_at' => '2020-08-08 13:55:15',
            ),
            38 => 
            array (
                'id' => 39,
                'brand' => 'Veritatis.',
                'sku' => 'dK2LaKFn9b',
                'name' => 'Quod qui.',
                'slug' => 'quod-qui',
                'description' => 'Nam labore aut pariatur necessitatibus consequuntur quidem et iusto est ut accusantium sed nihil molestias non dolorem qui enim praesentium similique sunt maxime doloribus est qui.',
                'quantity' => 17,
                'weight' => NULL,
                'price' => '633.00',
                'sale_price' => '440.00',
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 2,
                'created_at' => '2020-08-08 13:55:15',
                'updated_at' => '2020-08-08 13:55:15',
            ),
            39 => 
            array (
                'id' => 40,
                'brand' => 'Omnis magni.',
                'sku' => 'UPICXLqKyS',
                'name' => 'Enim ratione cupiditate.',
                'slug' => 'enim-ratione-cupiditate',
                'description' => 'Quisquam eius et et nihil rerum dolorem non pariatur autem impedit quos error.',
                'quantity' => 92,
                'weight' => NULL,
                'price' => '502.00',
                'sale_price' => '469.00',
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 3,
                'created_at' => '2020-08-08 13:55:15',
                'updated_at' => '2020-08-08 13:55:15',
            ),
            40 => 
            array (
                'id' => 41,
                'brand' => 'Qui unde.',
                'sku' => 'rMtlvvUeYh',
                'name' => 'Fugit quis incidunt.',
                'slug' => 'fugit-quis-incidunt',
                'description' => 'Modi atque quam odio eum facere sint eligendi velit adipisci qui velit dolores veritatis quas possimus est omnis omnis.',
                'quantity' => 62,
                'weight' => NULL,
                'price' => '599.00',
                'sale_price' => NULL,
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 1,
                'created_at' => '2020-08-08 13:55:15',
                'updated_at' => '2020-08-08 13:55:15',
            ),
            41 => 
            array (
                'id' => 42,
                'brand' => 'Molestias.',
                'sku' => 'YjXZXIOTjs',
                'name' => 'Quos totam quia.',
                'slug' => 'quos-totam-quia',
                'description' => 'Corporis dolores et et animi excepturi laborum a molestiae dolor voluptas qui rerum inventore voluptatem.',
                'quantity' => 82,
                'weight' => NULL,
                'price' => '185.00',
                'sale_price' => '269.00',
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 3,
                'created_at' => '2020-08-08 13:55:15',
                'updated_at' => '2020-08-08 13:55:15',
            ),
            42 => 
            array (
                'id' => 43,
                'brand' => 'Velit dolor.',
                'sku' => '68GrGbE3LF',
                'name' => 'Odit facere.',
                'slug' => 'odit-facere',
                'description' => '<p>Et possimus aut ea mollitia magnam eaque sed consequatur consequuntur ea excepturi soluta praesentium.</p>',
                'quantity' => 98,
                'weight' => NULL,
                'price' => '698.00',
                'sale_price' => NULL,
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 3,
                'created_at' => '2020-08-08 13:55:16',
                'updated_at' => '2020-08-08 14:03:07',
            ),
            43 => 
            array (
                'id' => 44,
                'brand' => 'Eius incidunt.',
                'sku' => 'aWNp6GkjvP',
                'name' => 'Enim sint tempora.',
                'slug' => 'enim-sint-tempora',
                'description' => 'Et quae aperiam quia voluptate id voluptas facilis rerum qui voluptatem omnis cumque adipisci ut ea corrupti a recusandae et vero vel necessitatibus beatae vel cumque.',
                'quantity' => 28,
                'weight' => NULL,
                'price' => '279.00',
                'sale_price' => '329.00',
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 3,
                'created_at' => '2020-08-08 13:55:16',
                'updated_at' => '2020-08-08 13:55:16',
            ),
            44 => 
            array (
                'id' => 45,
                'brand' => 'Sit.',
                'sku' => 'uiXYroSOlD',
                'name' => 'Eligendi corporis libero.',
                'slug' => 'eligendi-corporis-libero',
                'description' => 'Quia iste est excepturi veritatis consequatur aliquam consectetur id ipsa aliquid beatae eum fugiat tempora qui sed facilis.',
                'quantity' => 52,
                'weight' => NULL,
                'price' => '851.00',
                'sale_price' => NULL,
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 2,
                'created_at' => '2020-08-08 13:55:16',
                'updated_at' => '2020-08-08 13:55:16',
            ),
            45 => 
            array (
                'id' => 46,
                'brand' => 'A eum.',
                'sku' => 'oqtf66NCvM',
                'name' => 'Qui architecto.',
                'slug' => 'qui-architecto',
                'description' => 'Aut eos nulla quas id esse sint perferendis beatae repellat maiores eius sapiente quam facere magnam a veniam et error.',
                'quantity' => 55,
                'weight' => NULL,
                'price' => '297.00',
                'sale_price' => NULL,
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 1,
                'created_at' => '2020-08-08 13:55:16',
                'updated_at' => '2020-08-08 13:55:16',
            ),
            46 => 
            array (
                'id' => 47,
                'brand' => 'Illum provident.',
                'sku' => '3EMGus8K2S',
                'name' => 'Et non sint.',
                'slug' => 'et-non-sint',
                'description' => 'Laborum vitae totam ut vel ducimus facere illo omnis quo natus est officia tempora dolor commodi voluptas aut dolores vel.',
                'quantity' => 10,
                'weight' => NULL,
                'price' => '330.00',
                'sale_price' => NULL,
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 1,
                'created_at' => '2020-08-08 13:55:16',
                'updated_at' => '2020-08-08 13:55:16',
            ),
            47 => 
            array (
                'id' => 48,
                'brand' => 'Et.',
                'sku' => 'PLpyzV5kGK',
                'name' => 'Quia eligendi atque.',
                'slug' => 'quia-eligendi-atque',
                'description' => 'Nihil explicabo magnam in ipsum accusamus natus quo accusantium illum autem hic voluptate est quam et qui cumque et quia qui eius qui tenetur.',
                'quantity' => 74,
                'weight' => NULL,
                'price' => '391.00',
                'sale_price' => '196.00',
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 2,
                'created_at' => '2020-08-08 13:55:16',
                'updated_at' => '2020-08-08 13:55:16',
            ),
            48 => 
            array (
                'id' => 49,
                'brand' => 'Est qui.',
                'sku' => '8cIFFIJOlb',
                'name' => 'Et et est.',
                'slug' => 'et-et-est',
                'description' => 'Ab aliquam eos necessitatibus odit est et quaerat occaecati optio facere et est quidem fugiat quisquam ut aut consequatur iure vero corrupti commodi sit perferendis repudiandae.',
                'quantity' => 70,
                'weight' => NULL,
                'price' => '170.00',
                'sale_price' => '322.00',
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 2,
                'created_at' => '2020-08-08 13:55:16',
                'updated_at' => '2020-08-08 13:55:16',
            ),
            49 => 
            array (
                'id' => 50,
                'brand' => 'Voluptatem.',
                'sku' => 'EZks28QEOq',
                'name' => 'Voluptatibus modi unde.',
                'slug' => 'voluptatibus-modi-unde',
                'description' => 'Veritatis facilis dolores culpa perferendis voluptatum ipsam sit laborum ea laboriosam dolores quis in molestiae hic corporis ut.',
                'quantity' => 11,
                'weight' => NULL,
                'price' => '319.00',
                'sale_price' => '239.00',
                'status' => 1,
                'featured' => 0,
                'rating' => NULL,
                'cover_image' => 'products/basket.jpg',
                'images' => NULL,
                'shop_id' => 3,
                'created_at' => '2020-08-08 13:55:16',
                'updated_at' => '2020-08-08 13:55:16',
            ),
        ));
        
        
    }
}